### PR TITLE
Add readme.md & requirements.txt

### PR DESCRIPTION
**Pull request by beomjunshin-ben**

### CODE REVIEW

**Comment by beomjunshin-ben** [comment]
test please

**Comment by beomjunshin-ben** [comment]
test please

**Comment by beomjunshin-ben** [comment]
test please

**Comment by beomjunshin-ben** [comment]
test please

**Comment by beomjunshin-ben** [comment]
test please

**Comment by beomjunshin-ben** [comment]
test please

**Comment by beomjunshin-ben** [comment]
test please

**Comment by beomjunshin-ben** [comment]
test please

**Comment by beomjunshin-ben** [comment]
test please

**Comment by beomjunshin-ben** [comment]
test please

**Comment by beomjunshin-ben** [comment]
test please

**Comment by beomjunshin-ben** [comment]
test please.

**Comment by beomjunshin-ben** [comment]
test please

**Comment by beomjunshin-ben** [comment]
test please

**Comment by beomjunshin-ben** [comment]
test please

**Comment by beomjunshin-ben** [comment]
test please

**Review by sdalbsoo — APPROVED** [review]

**Pull request merged**
